package client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-18T21:26:33.862+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.example.org/Motooprema/", name = "MotoopremaPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MotoopremaPortType {

    @WebMethod(action = "http://www.example.org/Motooprema/vratiSveKategorije")
    @WebResult(name = "kategorijeResponse", targetNamespace = "http://www.example.org/Motooprema/", partName = "out")
    public KategorijeType vratiSveKategorije(
        @WebParam(partName = "in", name = "kategorijeRequest", targetNamespace = "http://www.example.org/Motooprema/")
        java.lang.String in
    );

    @WebMethod
    @WebResult(name = "kupiResponse", targetNamespace = "http://www.example.org/Motooprema/", partName = "out")
    public boolean kupiOpremu(
        @WebParam(partName = "in", name = "kupiRequest", targetNamespace = "http://www.example.org/Motooprema/")
        java.lang.String in
    );

    @WebMethod
    @WebResult(name = "novaResponse", targetNamespace = "http://www.example.org/Motooprema/", partName = "out")
    public boolean sacuvajOpremu(
        @WebParam(partName = "opremaType", name = "novaRequest", targetNamespace = "http://www.example.org/Motooprema/")
        OpremaType opremaType
    );

    @WebMethod
    @WebResult(name = "opremaResponse", targetNamespace = "http://www.example.org/Motooprema/", partName = "out")
    public OpremeType vratiOpremuIzKategorije(
        @WebParam(partName = "in", name = "opremaRequest", targetNamespace = "http://www.example.org/Motooprema/")
        java.lang.String in
    );
}
