package client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-18T21:26:33.907+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "Motooprema", 
                  wsdlLocation = "http://localhost:8080/SOAP_Motooprema_Service/MotoopremaPortType?wsdl",
                  targetNamespace = "http://www.example.org/Motooprema/") 
public class Motooprema extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Motooprema/", "Motooprema");
    public final static QName MotoopremaPortTypeImplPort = new QName("http://www.example.org/Motooprema/", "MotoopremaPortTypeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAP_Motooprema_Service/MotoopremaPortType?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Motooprema.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAP_Motooprema_Service/MotoopremaPortType?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Motooprema(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Motooprema(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Motooprema() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Motooprema(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Motooprema(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Motooprema(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MotoopremaPortType
     */
    @WebEndpoint(name = "MotoopremaPortTypeImplPort")
    public MotoopremaPortType getMotoopremaPortTypeImplPort() {
        return super.getPort(MotoopremaPortTypeImplPort, MotoopremaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MotoopremaPortType
     */
    @WebEndpoint(name = "MotoopremaPortTypeImplPort")
    public MotoopremaPortType getMotoopremaPortTypeImplPort(WebServiceFeature... features) {
        return super.getPort(MotoopremaPortTypeImplPort, MotoopremaPortType.class, features);
    }

}
