package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-06-18T01:22:18.791+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "Motooprema", 
                  wsdlLocation = "file:/C:/Users/Novica/Desktop/Vezbe-DS/WorkspaceDS/SOAP_Motooprema_Service/spec/Motooprema.wsdl",
                  targetNamespace = "http://www.example.org/Motooprema/") 
public class Motooprema extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/Motooprema/", "Motooprema");
    public final static QName MotoopremaPort = new QName("http://www.example.org/Motooprema/", "MotoopremaPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Novica/Desktop/Vezbe-DS/WorkspaceDS/SOAP_Motooprema_Service/spec/Motooprema.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Motooprema.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Novica/Desktop/Vezbe-DS/WorkspaceDS/SOAP_Motooprema_Service/spec/Motooprema.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Motooprema(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Motooprema(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Motooprema() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Motooprema(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Motooprema(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Motooprema(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MotoopremaPortType
     */
    @WebEndpoint(name = "MotoopremaPort")
    public MotoopremaPortType getMotoopremaPort() {
        return super.getPort(MotoopremaPort, MotoopremaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MotoopremaPortType
     */
    @WebEndpoint(name = "MotoopremaPort")
    public MotoopremaPortType getMotoopremaPort(WebServiceFeature... features) {
        return super.getPort(MotoopremaPort, MotoopremaPortType.class, features);
    }

}
